# https://travis-ci.org/jkbrzt/httpie
sudo: false

language: python
os:
  - linux

env:
  global:
    - NEWEST_PYTHON=3.4

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3

matrix:
  include:
    # https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
    - os: osx
      language: generic

script:
  - make

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew install python
    fi

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux']]; then
      pip install python-coveralls && coveralls
    fi
