# https://travis-ci.org/jkbrzt/httpie
sudo: false
os:
  - linux
env:
  global:
  - NEWEST_PYTHON=3.4
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - pypy3

matrix:
  include:
    # https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
    - os: osx
      language: generic

script:
  - make
after_success:
  - [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux']] && pip install python-coveralls && coveralls
