# https://travis-ci.org/jkbrzt/httpie
sudo: false

language: python
os:
  - linux

env:
  global:
    - NEWEST_PYTHON=3.5

python:
  - 2.6
  - 2.7
  - pypy
  - 3.5
  - pypy3

matrix:

  include:
    # https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
    - os: osx
      language: generic
      env:
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - BREW_INSTALL=python
        - TOXENV=py27
    - os: osx
      language: generic
      env:
        - BREW_INSTALL=python3
        - TOXENV=py35

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ -n "$BREW_INSTALL" ]]; then
        brew install "$BREW_INSTALL"
      fi
      sudo pip install tox
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      make
    else
      tox -e "$TOXENV"
    fi

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux']]; then
      pip install python-coveralls && coveralls
    fi
