# https://travis-ci.org/jkbrzt/httpie
sudo: false

language: python
os:
  - linux

env:
  global:
    - NEWEST_PYTHON=3.5

python:
  - 2.6
  - 2.7
  - pypy
  - 3.5
  - pypy3

matrix:

  include:

    # Manually defined OS X builds
    # https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)

    # Stock OSX Python
    - os: osx
      language: generic
      env:
        - TOXENV=py27

    # Latest Python 2.x from Homebrew
    - os: osx
      language: generic
      env:
        - TOXENV=py27
        - BREW_INSTALL=python

    # Latest Python 3.x from Homebrew
    - os: osx
      language: generic
      env:
        - TOXENV=py35
        - BREW_INSTALL=python3

install:
  - brew update
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ -n "$BREW_INSTALL" ]]; then
        brew install "$BREW_INSTALL"
      fi
      sudo pip install tox
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      make
    else
      PATH="/usr/local/bin:$PATH" tox -e "$TOXENV"
    fi

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux']]; then
      pip install python-coveralls && coveralls
    fi
